version: "3.9"
services:
  db:
    image: postgres:16
    container_name: jobtrack_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtrack
      POSTGRES_HOST_AUTH_METHOD: trust

    ports:
      - "5432:5432"
    volumes:
      - jobtrack_pgdata:/var/lib/postgresql/data

volumes:
  jobtrack_pgdata:
